### ISSUE TITLE
Make epinio-ui chart a subchart of epinio

### ISSUE THREAD

**Issue by jimmykarily** [epinio/helm-charts#110]
Follow up of: https://github.com/epinio/ui/issues/68

**Comment by manno** [comment]
Can be conditional, so we probably have something on Epinio like ui=true and if that is set, we add the / route to the main ingress.

**Comment by jimmykarily** [comment]
Yes that's what we do for the rest of them:

https://github.com/epinio/helm-charts/blob/main/chart/epinio/values.yaml#L88
https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags

**Comment by manno** [comment]
This has an example for the combined ingress: https://github.com/epinio/helm-charts/pull/102
