### ISSUE TITLE
Use `extraDeploy` to put host information in the default catalog service secrets

### ISSUE THREAD

**Issue by jimmykarily** [epinio/helm-charts#223]
The default bitnami helm chart we use for the out-of-the-box catalog services, don't put any information about the host (the url) of the created service in the secrets. When the Epinio user binds the service instance to an app, the configurations are simply the Opaque secrets that belong to the helm release. This means, the Epinio user doesn't know what the host for their service (e.g. MySQL) is.

One way to solve this without "forking" the upstream charts is by using the `extraDeploy` value supported by bitnami helm charts. It's the same mechanism [we used to clean up PVCs](https://github.com/epinio/helm-charts/blob/81863ce5863272a591a463ebef11760c9e27781a/chart/epinio/templates/_helpers.tpl#L45). We could use it to create an additional secret that will hold the hostname (internal kubernetes DNS) for the service. For the development services we deploy that are supposed to live on the same cluster with the apps, this should be fine.

**Comment by andreas-kupries** [comment]
Superseded by our display of the service in the service details
