### ISSUE TITLE
Fix epiniod pipeline

### ISSUE THREAD

**Issue by jimmykarily** [epinio/helm-charts#250]
After releasing v1.0.1 of the helm chart, [the epiniod pipeline]() didn't trigger automatically. I had to [trigger it manually](https://github.com/epinio/helm-charts/runs/7252226597?check_suite_focus=true) and it seemed to have released something but the tag is wrong:

```
docker run -it --privileged  ghcr.io/epinio/epiniod:epinio-1.0.1
...
Release "epinio" does not exist. Installing it now.
Error: failed to download "epinio/epinio" at version "epinio-1.0.1"
...
```

Not sure why, but this doesn't seem to work: https://github.com/epinio/helm-charts/blob/e64ad567140601d4ec515fa4b1f67e4f3abedb6d/.github/workflows/build-epiniod.yml#L5-L6

**Comment by andreas-kupries** [comment]
@jimmykarily Look at the indent of

https://github.com/epinio/helm-charts/blob/main/.github/workflows/build-epiniod.yml#L3-L6

I suspect that the `release` has to be indented to be part of the `workflow_dispatch`.

I will make a PR for you to look at.

I cannot say anything about the tagging.

**Comment by andreas-kupries** [comment]
Or not ... Should have read https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release and https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch first ...

These are two independent triggers :(

**Comment by andreas-kupries** [comment]
No PR forthcoming. After reading the documentation some more the definition should be correct. Trigger on published release, or trigger manually ...

As for the tag ... The pipeline looks to be triggered for all helm-chart releases. Which may not be epinio chart, right ?
How does the pipeline detect that it was triggered for an epinio release and not epinio-application, etc. ?
Could this interfere with determination of the tag ?

Or does it always build epinio, regardless of which release was published ?

  - Apparently yes (`context: images/.`, and `Dockerfile` in that directory)

It still seems to pull tag information out of the event, which may be for a different chart, whose tag is not known for the epinio chart ... And when you trigger things manually, what tag info do you get in that case ? Do you even get any ?

**Comment by andreas-kupries** [comment]
Hm ... I am unable to confirm the issue with the tag ...

```
d pull ghcr.io/epinio/epiniod:epinio-1.0.1
epinio-1.0.1: Pulling from epinio/epiniod
59bf1c3509f3: Already exists 
1ea03e1895df: Pull complete 
1ff98835b055: Pull complete 
a3f2dd7b7d65: Pull complete 
d182b62d4a35: Pull complete 
d7a57db2abd7: Pull complete 
73490af52bd3: Pull complete 
7d28806efd0e: Pull complete 
b97fd78563ff: Pull complete 
ffaf1aff7f0b: Pull complete 
403593afa76f: Pull complete 
6ab5819d7de6: Pull complete 
c0bf4ecf5dcb: Pull complete 
5ba577caac7e: Pull complete 
876afc513940: Pull complete 
1120a6b53423: Pull complete 
3b731c0cccee: Pull complete 
Digest: sha256:5788f660c9e6a604b2cba25a9f9f961166417dd032d0b954abc61fe48ea40ec7
Status: Downloaded newer image for ghcr.io/epinio/epiniod:epinio-1.0.1
ghcr.io/epinio/epiniod:epinio-1.0.1
work@tagetarl:~/SUSE/dev/epinio/helm-charts> docker run -it --privileged  ghcr.io/epinio/epiniod:epinio-1.0.1
Waiting for container runtime to be ready...Done
Creating a cluster for epinio
FATA[0000] No nodes found for given cluster             
INFO[0000] Prep: Network                                
INFO[0000] Created network 'k3d-epinio'                 
INFO[0000] Created image volume k3d-epinio-images       
INFO[0000] Starting new tools node...                   
INFO[0001] Creating node 'k3d-epinio-server-0'          
INFO[0001] Pulling image 'docker.io/rancher/k3d-tools:5.3.0' 
INFO[0002] Pulling image 'docker.io/rancher/k3s:v1.22.6-k3s1' 
INFO[0004] Starting Node 'k3d-epinio-tools'             
^C
```

The image is listed as `7 weeks ago` ... Maps to around July 11. Ticket is July 8.
Note: I used the information from the [latest run of the action per the history](https://github.com/epinio/helm-charts/actions/workflows/build-epiniod.yml) ... That was July 8.
So no other build which could have created the image with tag, invalidating the description.

Best idea I have now is that there was a window after the upload where the image+tag were not yet available for pulling.

**Comment by andreas-kupries** [comment]
I believe now that the tag issue was a spurious thing and that the manual action indeed worked.
This still leaves the issue with the triggering not happening.

**Comment by jimmykarily** [comment]
@andreas-kupries I'm not a 100% sure anymore but I think I tagged the image locally and pushed it because the pipeline wasn't working. Don't assume the pipeline pushed the current tag.

**Comment by jimmykarily** [comment]
> I see. So my best bet to look at things is to manually trigger it again, and hope for a different tag ?

I think so. There is a newer version after all. You can at least debug the tagging using that.

**Comment by andreas-kupries** [comment]
So. Triggered the flow, from branch main.
I get 
```
  sha: 3ece8553d285058bd2cfa7feb62b9e57a51f3b86
  ref: refs/heads/main
```
in the context info of the `Docker meta` step.
This translated into the tag `3ece855`.
Pulling `ghcr.io/epinio/epiniod:3ece855` worked.
Note that there is no `epinio-(version)` tag.
Looking back to the other action run the ref was `ref: refs/tags/epinio-1.0.1`.
I.e. the action was run from a tagged commit, maybe ?
I.e. the commit the release was based on ?

Ah, I see that I can trigger for a tag, not just branches.
Let me try that.
Yes, context now has
```
sha: c097eb4d9604018986daf827a38fe2bfe68b02b3
ref: refs/tags/epinio-1.1.0
```
Chosen tags are `epinio-1.1.0`, `c097eb4`, and `latest`.

Pulling
  - `c097eb4` :heavy_check_mark: 
  - `epinio-1.1.0` :heavy_check_mark: (Fast, because the layers were already local)
  - `latest` Does nothing. Keeps to the `epinio-1.0.1`. Untagging latest locally and re-pull ... No change.

With the exception of `latest` the tagging looks to be ok.

**Comment by andreas-kupries** [comment]
Updated https://github.com/epinio/epinio/issues/1700 description with a step to check the epiniod workflow, and trigger manually if needed.

As of a moment ago the `latest` tag points to the new image I created yesterday.
I have not done anything since yesterday's workflow build. I.e. no manual tagging.
Has somebody else done such tagging ?
Given the `rpardini/docker-registry-proxy:0.6.0` I have running I wonder if the issue was this cache.

**Comment by andreas-kupries** [comment]
"Fix" in https://github.com/epinio/epinio/pull/1703. Extends release check list with item to watch the epiniod pipeline

**Comment by jimmykarily** [comment]
>  Has somebody else done such tagging ? 

not me

**Comment by andreas-kupries** [comment]
Ok. Then I am blaming this on the cache needing some time until it actually rechecks for a newer image.

**Comment by jimmykarily** [comment]
While releasing v1.2.0, it appears that the pipeline is still broken:

- The pipeline didn't trigger upon release
- When we triggered manually, the built image just got tagged with the commit id (no version, no `latest`)
- When this command is run:
  ```
    docker run --name epiniod -it --privileged -p 443:443 ghcr.io/epinio/epiniod:b9115cc
  ``` 
  we get an error: `Error: failed to download "epinio/epinio" at version "main"` (probably because the build-arg was set to the wrong thing: `main` when we triggered with "workflow dispatch")

**Comment by jimmykarily** [comment]
If we decide to merge [the PR](https://github.com/epinio/helm-charts/pull/275), maybe I should re-phrase the release issue template item: https://github.com/epinio/epinio/blob/main/.github/ISSUE_TEMPLATE/release_checklist.yaml (since we know it doesn't trigger)
