### ISSUE TITLE
Missing helm chart value for custom email address used by tlsIssuer

### ISSUE THREAD

**Issue by thehejik** [epinio/helm-charts#348]
When installing epinio over helm chart user can use `-- set global.tlsIssuer=letsencrypt-production` but there is no way how to specify an email for DNS/cert notifications from the Issuer, it is using hardcoded email `epinio@suse.com` instead.

The hardcoded address is visible for eg. in `kubectl get clusterissuers.cert-manager.io letsencrypt-production -o yaml` output as   `.spec.acme.email` value.

So something like `--set global.tlsIssuer.email=<custom email>` would be nice.

Found in epinio v1.6.1

**Comment by andreas-kupries** [comment]
Heh. The `values.yaml` contains

```
#The email address you are planning to use for getting notifications about your certificates.
email: "epinio@suse.com"
```

at the very top. This is used in

```
./chart/epinio/templates/cluster-issuers.yaml:18:    email: {{ .Values.email }}
```

So, not truly hardcoded. Just not in the place it was expected at. The `questions.yaml` references it.

**Comment by thehejik** [comment]
Successfully verified on EKS by using recent `helm-charts` code with fixes. The documentation also looks good.

Requirements: EKS cluster, cert-manager, ingress-controller, public domain zone with CNAME records pointing to ELB endpoint.

```
helm upgrade --install epinio --namespace epinio ./chart/epinio  --set skipTraefik=true --set global.domain=mydomain --create-namespace  --set global.tlsIssuer=letsencrypt-production --set global.tlsIssuerEmail=myemail@suse.com
```

After a while the ingress should be active and there are no other resources than in Ready state.

The custom email value can be verified then by calling - it shouldn't return `epinio@suse.com`:
```
kubectl get clusterissuers.cert-manager.io letsencrypt-production -o jsonpath='{.spec.acme.email}'
> myemail@suse.com
```
