### ISSUE TITLE
Feature Request: expose appChart url through values

### ISSUE THREAD

**Issue by riqueps** [epinio/helm-charts#440]
### Is your feature request related to a problem?

For complex environments a custom appChart may be necessary, eg: add custom ingress annotation, select the ingress controller based on the domain, etc...

For now we are able to create a new appChart and turn it default, but this is a local setting, as documented [here](https://docs.epinio.io/howtos/using_custom_appcharts).

So, by mapping the appChart helm url through values, epinio admins can setup a default system wide custom appChart

File: [default-app-chart.yaml
](https://github.com/epinio/helm-charts/blob/main/chart/epinio/templates/default-app-chart.yaml)

Paramter: helmChart: https://xxxx.xxx.xx

### Solution you'd like

Map it to Values.yaml file, eg:

```
appChart:
  url: https://github.com/epinio/helm-charts/releases/download/epinio-application-0.1.26/epinio-application-0.1.26.tgz
```

### Alternatives you've considered

For now we are manually editing the `standard` appChart

**Comment by enrichman** [comment]
Hi @riqueps, it seems a nice and easy feature. We are going to schedule this for the next release. :+1:
