### ISSUE TITLE
helm-charts releaser should have a different workflow for each chart

### ISSUE THREAD

**Issue by jimmykarily** [epinio/helm-charts#49]
Because when we try to release `epinio` chart, even though the `epinio-installer` doesn't have a bumped version, the releaser tries to create a new release and fails because the version is not bumped. We should have a different pipeline to release each of the 3 charts.

**Comment by juadk** [comment]
@jimmykarily I wonder if we still need this with my last PR #52 merged.
Because now, I think we can bump all versions in only one PR and then, execute the release workflow. I feel like I'm missing something obvious...

**Comment by jimmykarily** [comment]
The only thing that we miss with what you describe is the ability to release only the epinio helm chart, without releasing the epinio-installer one. If we don't bump the epinio-installer chart version and we trigger the release workflow, the pipeline will fail.

On the other hand, when we have a new epinio chart then we usually want a new epinio-installer chart to consume it. I'm not sure if we need the extra flexibility.

**Comment by juadk** [comment]
Yes I agree with the process you just described, I'm still thinking...
I've tried to parameterize the workflow with the chart we want to release but it doesn't work as expected....
![image](https://user-images.githubusercontent.com/6025636/147098416-b3764fba-0b5a-4f78-b1ed-0baa3b7f10e7.png)
```
       - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: chart/${{ github.event.inputs.chart }}
```
It doesn't take my custom charts_dir into account and still check all the charts...

**Comment by juadk** [comment]
Maybe that's not possible due to difficulties to manage the index.yaml file.
Let's see how the next release will behave then.

**Comment by jimmykarily** [comment]
since we always bump both charts together, let's close this issue until it's really a problem
