### ISSUE TITLE
minio-operator handshake errors

### ISSUE THREAD

**Issue by jimmykarily** [epinio/helm-charts#53]
On an otherwise working installation of epinio-installer (v0.3.4), the minio operator pod prints these errors:

```
│ 2021/12/23 12:38:41 http: TLS handshake error from 10.42.0.1:20086: remote error: tls: bad certificate                                                                    │
│ 2021/12/23 12:38:42 http: TLS handshake error from 10.42.0.1:23418: remote error: tls: bad certificate                                                                    │
│ 2021/12/23 12:38:43 http: TLS handshake error from 10.42.0.1:56483: remote error: tls: bad certificate                                                                    │
│ 2021/12/23 12:38:44 http: TLS handshake error from 10.42.0.1:25938: remote error: tls: bad certificate                                                                    │
│ 2021/12/23 12:38:45 http: TLS handshake error from 10.42.0.1:18890: remote error: tls: bad certificate    
```

Maybe relevant: The minio operator is not in the linkerd mesh while the tenant is. I think the tenant is what Epinio server talks to when uploading and downloading blobs so it has to be in the mesh to have encrypted communication. Could that be the reason for the above error though? Is the operator trying to talk to the tenant or the other way round?

**Comment by andreas-kupries** [comment]
Confirmed the presence of these log entries.
I see them continuously, about every second.
As the log entry says `from IP:...` I suspect something pings the operator every second and closes the connection before doing anything with it.
It feels like a k8s probe.
On the other side,  I see no probes specified in the pod spec.

**Comment by andreas-kupries** [comment]
The logs mentions an IP address for the originator of the requests ... Learning a bit more I found that the `status.podIP` field for pods can be used to determine the IP address of each pod in the system. Using

>  kubectl get pods --all-namespaces -o yaml|grep -v '[fk]:' |grep podIP

I find that no pod in the system has that IP address. The found and missing IP are however in the same subnet, as specified by the k3d kube node.

To be concrete ... The net is `10.42.0.0/24`, the origin IP in the log is `10.42.0.1`, and I see pod IPs from `.2` to `.33` (with gaps).

Now I am wondering if the `.1` is just the kube node. That would make sense. I.e. the kube admin system checking on the pod with a default probe, as the user did not specify anything custom.

**Comment by andreas-kupries** [comment]
Side note: minio-operator is `.22`.

Dumping all resources and searching for IP addresses ... I found the operator and others, nothing references `.1`.
I am pretty convinced now that none of the user resources are the origin of this IP address and connection, leaving only the kube foundational pieces.

@jimmykarily Based on the above I would like to close this issue as not being about a true error. kube probes the pods with some default which opens and closes the port, and nothing more. This is an incomplete tls handshake, and so the server reports it as such.

**Comment by andreas-kupries** [comment]
:eyes: ... ... ... ... I am not sure. By my reading that issue is about problems with certificates. 

Oh. Wait. Our description above also mentions the `bad cert` ... 
and in my setup (local k3s/k3d) the failed handshake was ... also `bad cert`.

:facepalm: I was looking into the completely wrong direction, it seems.

So, what is our operator version ?

**Comment by ankursgupta** [comment]
+1

```
$ kubectl minio version
v4.4.4

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jimmykarily** [comment]
Minio is going away: 

https://github.com/epinio/epinio/issues/1157
https://github.com/epinio/epinio/discussions/1103#discussioncomment-2073459

Let's not fix this.
