### ISSUE TITLE
Fix "domain" helm value

### ISSUE THREAD

**Issue by jimmykarily** [epinio/helm-charts#56]
Docs are wrong: https://docs.epinio.io/installation/install_epinio_auto.html#deploy-epinio

the `epinio-installer` helm chart [needs the `domain` value](https://github.com/epinio/helm-charts/blob/main/chart/epinio-installer/values.yaml#L15). The `epinio` helm chart [uses the `systemDomain` value](https://github.com/epinio/helm-charts/blob/main/chart/epinio/values.yaml#L12). This is confusing.

Let's use the same value in both cases and update docs.

**Comment by andreas-kupries** [comment]
I choose `domain`. Any objections ?
